<?xml version="1.0" encoding="utf-8"?><Database Name="Cafe" Class="DataLQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Cafe.mdf;Integrated Security=True" SettingsObjectName="DataCf.Properties.Settings" SettingsPropertyName="CafeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Ban" Member="Bans">
    <Type Name="Ban">
      <Column Name="TenBan" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="SoHD" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Association Name="HoaDon_Ban" Member="HoaDon" ThisKey="SoHD" OtherKey="SoHD" Type="HoaDon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TruLuong" Member="TruLuongs">
    <Type Name="TruLuong">
      <Column Name="MaT" Type="System.Decimal" DbType="Decimal(15,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayThu" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="LyDoTru" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="MaCong" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Association Name="TienCong_TruLuong" Member="TienCong" ThisKey="MaCong" OtherKey="MaCong" Type="TienCong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BangCong" Member="BangCongs">
    <Type Name="BangCong">
      <Column Name="MaBC" Type="System.Decimal" DbType="Decimal(6,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Thang" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Nam" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoNgay" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="LuongPhaiTra" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="BangCong_TienCong" Member="TienCongs" ThisKey="MaBC" OtherKey="MaBC" Type="TienCong" />
    </Type>
  </Table>
  <Table Name="dbo.BanHang" Member="BanHangs">
    <Type Name="BanHang">
      <Column Name="SoHD" Type="System.Decimal" DbType="Decimal(15,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="HoaDon_BanHang" Member="HoaDon" ThisKey="SoHD" OtherKey="SoHD" Type="HoaDon" IsForeignKey="true" />
      <Association Name="MatHang_BanHang" Member="MatHang" ThisKey="MaHang" OtherKey="MaHang" Type="MatHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BaoCao" Member="BaoCaos">
    <Type Name="BaoCao">
      <Column Name="MaBC" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="NgayGio" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Association Name="NhanVien_BaoCao" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ca" Member="Cas">
    <Type Name="Ca">
      <Column Name="MaCa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenCa" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BatDau" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="KetThuc" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Association Name="Ca_ChamCong" Member="ChamCongs" ThisKey="MaCa" OtherKey="MaCa" Type="ChamCong" />
      <Association Name="Ca_Lam" Member="Lams" ThisKey="MaCa" OtherKey="MaCa" Type="Lam" />
    </Type>
  </Table>
  <Table Name="dbo.ChamCong" Member="ChamCongs">
    <Type Name="ChamCong">
      <Column Name="MaCong" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaCa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayThu" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Ca_ChamCong" Member="Ca" ThisKey="MaCa" OtherKey="MaCa" Type="Ca" IsForeignKey="true" />
      <Association Name="TienCong_ChamCong" Member="TienCong" ThisKey="MaCong" OtherKey="MaCong" Type="TienCong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChucVu" Member="ChucVus">
    <Type Name="ChucVu">
      <Column Name="MaCV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenCV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QL" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="ChucVu_NhanVien" Member="NhanViens" ThisKey="MaCV" OtherKey="MaCV" Type="NhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.CungCap" Member="CungCaps">
    <Type Name="CungCap">
      <Column Name="MaHang" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNCC" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GiaNhap" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="MatHang_CungCap" Member="MatHang" ThisKey="MaHang" OtherKey="MaHang" Type="MatHang" IsForeignKey="true" />
      <Association Name="NhaCC_CungCap" Member="NhaCC" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HangSo" Member="HangSos">
    <Type Name="HangSo">
      <Column Name="Ten" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GiaTri" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="SoHD" Type="System.Decimal" DbType="Decimal(15,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ngay" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="GMo" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="GDong" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="TienNuoc" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="VAT" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="GiamGia" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TenBan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Association Name="HoaDon_Ban" Member="Bans" ThisKey="SoHD" OtherKey="SoHD" Type="Ban" />
      <Association Name="HoaDon_BanHang" Member="BanHangs" ThisKey="SoHD" OtherKey="SoHD" Type="BanHang" />
      <Association Name="NhanVien_HoaDon" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lam" Member="Lams">
    <Type Name="Lam">
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaCa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LN" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Association Name="Ca_Lam" Member="Ca" ThisKey="MaCa" OtherKey="MaCa" Type="Ca" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="NhanVien_Lam" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MatHang" Member="MatHangs">
    <Type Name="MatHang">
      <Column Name="MaHang" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Loai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Xoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="MatHang_BanHang" Member="BanHangs" ThisKey="MaHang" OtherKey="MaHang" Type="BanHang" />
      <Association Name="MatHang_CungCap" Member="CungCaps" ThisKey="MaHang" OtherKey="MaHang" Type="CungCap" />
      <Association Name="MatHang_Nhap" Member="Nhaps" ThisKey="MaHang" OtherKey="MaHang" Type="Nhap" />
    </Type>
  </Table>
  <Table Name="dbo.NhaCC" Member="NhaCCs">
    <Type Name="NhaCC">
      <Column Name="MaNCC" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaSoThue" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Xoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="NhaCC_CungCap" Member="CungCaps" ThisKey="MaNCC" OtherKey="MaNCC" Type="CungCap" />
      <Association Name="NhaCC_PhieuNhap" Member="PhieuNhaps" ThisKey="MaNCC" OtherKey="MaNCC" Type="PhieuNhap" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MucLuong" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NgayLam" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="MaCV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Xoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_BaoCao" Member="BaoCaos" ThisKey="MaNV" OtherKey="MaNV" Type="BaoCao" />
      <Association Name="NhanVien_HoaDon" Member="HoaDons" ThisKey="MaNV" OtherKey="MaNV" Type="HoaDon" />
      <Association Name="NhanVien_Lam" Member="Lams" ThisKey="MaNV" OtherKey="MaNV" Type="Lam" />
      <Association Name="NhanVien_PhieuNhap" Member="PhieuNhaps" ThisKey="MaNV" OtherKey="MaNV" Type="PhieuNhap" />
      <Association Name="NhanVien_PhieuThuChi" Member="PhieuThuChis" ThisKey="MaNV" OtherKey="MaNV" Type="PhieuThuChi" />
      <Association Name="NhanVien_TaiKhoan" Member="TaiKhoans" ThisKey="MaNV" OtherKey="MaNV" Type="TaiKhoan" />
      <Association Name="NhanVien_TienCong" Member="TienCongs" ThisKey="MaNV" OtherKey="MaNV" Type="TienCong" />
      <Association Name="ChucVu_NhanVien" Member="ChucVu" ThisKey="MaCV" OtherKey="MaCV" Type="ChucVu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Nhap" Member="Nhaps">
    <Type Name="Nhap">
      <Column Name="SoPhieu" Type="System.Decimal" DbType="Decimal(15,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MatHang_Nhap" Member="MatHang" ThisKey="MaHang" OtherKey="MaHang" Type="MatHang" IsForeignKey="true" />
      <Association Name="PhieuNhap_Nhap" Member="PhieuNhap" ThisKey="SoPhieu" OtherKey="SoPhieu" Type="PhieuNhap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuNhap" Member="PhieuNhaps">
    <Type Name="PhieuNhap">
      <Column Name="SoPhieu" Type="System.Decimal" DbType="Decimal(15,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="MaNCC" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Association Name="PhieuNhap_Nhap" Member="Nhaps" ThisKey="SoPhieu" OtherKey="SoPhieu" Type="Nhap" />
      <Association Name="NhaCC_PhieuNhap" Member="NhaCC" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCC" IsForeignKey="true" />
      <Association Name="NhanVien_PhieuNhap" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuThuChi" Member="PhieuThuChis">
    <Type Name="PhieuThuChi">
      <Column Name="SoPhieu" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ngay" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Loai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LyDo" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NguoiNhan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_PhieuThuChi" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="TenTK" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_TaiKhoan" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TienCong" Member="TienCongs">
    <Type Name="TienCong">
      <Column Name="MaCong" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="MaBC" Type="System.Decimal" DbType="Decimal(6,0) NOT NULL" CanBeNull="false" />
      <Column Name="TienCongLam" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TienTru" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TienLuong" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TienCong_TruLuong" Member="TruLuongs" ThisKey="MaCong" OtherKey="MaCong" Type="TruLuong" />
      <Association Name="TienCong_ChamCong" Member="ChamCongs" ThisKey="MaCong" OtherKey="MaCong" Type="ChamCong" />
      <Association Name="BangCong_TienCong" Member="BangCong" ThisKey="MaBC" OtherKey="MaBC" Type="BangCong" IsForeignKey="true" />
      <Association Name="NhanVien_TienCong" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_BanDHD" Member="vw_BanDHDs">
    <Type Name="vw_BanDHD">
      <Column Name="SoHD" Type="System.Decimal" DbType="Decimal(15,0) NOT NULL" CanBeNull="false" />
      <Column Name="Ngay" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="GMo" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="GDong" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="VAT" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="GiamGia" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TenBan" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_TtTk" Member="vw_TtTks">
    <Type Name="vw_TtTk">
      <Column Name="TenTK" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QL" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="TenND" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_BangCong" Member="vw_BangCongs">
    <Type Name="vw_BangCong">
      <Column Name="MaBC" Type="System.Decimal" DbType="Decimal(6,0) NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Thang" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Nam" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoNgay" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="LuongPhaiTra" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_BanHang" Member="vw_BanHangs">
    <Type Name="vw_BanHang">
      <Column Name="SoHD" Type="System.Decimal" DbType="Decimal(15,0) NOT NULL" CanBeNull="false" />
      <Column Name="MaHang" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_BaoCao" Member="vw_BaoCaos">
    <Type Name="vw_BaoCao">
      <Column Name="MaBC" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NgayGio" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_ChamCong" Member="vw_ChamCongs">
    <Type Name="vw_ChamCong">
      <Column Name="MaBC" Type="System.Decimal" DbType="Decimal(6,0) NOT NULL" CanBeNull="false" />
      <Column Name="MaCong" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Column Name="MaCa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenCa" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayThu" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_CungCap" Member="vw_CungCaps">
    <Type Name="vw_CungCap">
      <Column Name="MaHang" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaNCC" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GiaNhap" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_CungCapC" Member="vw_CungCapCs">
    <Type Name="vw_CungCapC">
      <Column Name="MaHang" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaNCC" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GiaNhap" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_CungCapCT" Member="vw_CungCapCTs">
    <Type Name="vw_CungCapCT">
      <Column Name="MaHang" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GiaNhap" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_CungCapHang" Member="vw_CungCapHangs">
    <Type Name="vw_CungCapHang">
      <Column Name="MaNCC" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GiaNhap" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_DmBan" Member="vw_DmBans">
    <Type Name="vw_DmBan">
      <Column Name="TenBan" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_DoanhThu" Member="vw_DoanhThus">
    <Type Name="vw_DoanhThu">
      <Column Name="Ngay" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="LyDo" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Loai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_HDtoDay" Member="vw_HDtoDays">
    <Type Name="vw_HDtoDay">
      <Column Name="SoHD" Type="System.Decimal" DbType="Decimal(15,0) NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_Lam" Member="vw_Lams">
    <Type Name="vw_Lam">
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaCa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenCa" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LN" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_LichLam" Member="vw_LichLams">
    <Type Name="vw_LichLam">
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LN" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="MaCa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenCa" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_ListTaiKhoan" Member="vw_ListTaiKhoans">
    <Type Name="vw_ListTaiKhoan">
      <Column Name="TenTK" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenCV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_ListTK" Member="vw_ListTKs">
    <Type Name="vw_ListTK">
      <Column Name="TenTK" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QL" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="TenND" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_LuongNV" Member="vw_LuongNVs">
    <Type Name="vw_LuongNV">
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Thang" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Nam" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TienLuong" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_MatHang" Member="vw_MatHangs">
    <Type Name="vw_MatHang">
      <Column Name="MaHang" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Loai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_NguoiDung" Member="vw_NguoiDungs">
    <Type Name="vw_NguoiDung">
      <Column Name="TenTK" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QL" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="TenND" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_NhaCC" Member="vw_NhaCCs">
    <Type Name="vw_NhaCC">
      <Column Name="MaNCC" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaSoThue" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_NhanVienCV" Member="vw_NhanVienCVs">
    <Type Name="vw_NhanVienCV">
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenCV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QL" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_Nhap" Member="vw_Nhaps">
    <Type Name="vw_Nhap">
      <Column Name="SoPhieu" Type="System.Decimal" DbType="Decimal(15,0) NOT NULL" CanBeNull="false" />
      <Column Name="MaHang" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaNhap" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_NVisQLnotTK" Member="vw_NVisQLnotTKs">
    <Type Name="vw_NVisQLnotTK">
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenCV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QL" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_PhieuChi" Member="vw_PhieuChis">
    <Type Name="vw_PhieuChi">
      <Column Name="SoPhieu" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ngay" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="LyDo" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NguoiNhan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_PhieuThu" Member="vw_PhieuThus">
    <Type Name="vw_PhieuThu">
      <Column Name="SoPhieu" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ngay" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="LyDo" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NguoiNhan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_SapLich" Member="vw_SapLiches">
    <Type Name="vw_SapLich">
      <Column Name="MaCa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenCa" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LN" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_TaiKhoan" Member="vw_TaiKhoans">
    <Type Name="vw_TaiKhoan">
      <Column Name="TenTK" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QL" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_TaiKhoanC" Member="vw_TaiKhoanCs">
    <Type Name="vw_TaiKhoanC">
      <Column Name="TenTK" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenCV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ql" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_DoUong" Member="vw_DoUongs">
    <Type Name="vw_DoUong">
      <Column Name="Ngay" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="MaHang" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Loai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CM" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.pr_XoaBangCong" Method="pr_XoaBangCong">
    <Parameter Name="maBC" Type="System.Decimal" DbType="Decimal(6,0)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fdayMonth" Method="fdayMonth" IsComposable="true">
    <Parameter Name="thang" Type="System.Int32" DbType="Int" />
    <Parameter Name="nam" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ft_XoaBC" Method="ft_XoaBC" IsComposable="true">
    <Parameter Name="maC" Type="System.Decimal" DbType="Decimal(6,0)" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.ft_FtruL" Method="ft_FtruL" IsComposable="true">
    <Parameter Name="i" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="c" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Decimal" />
  </Function>
  <Function Name="dbo.ft_KiemTraMk" Method="ft_KiemTraMk" IsComposable="true">
    <Parameter Name="tentk" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="mk" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.ft_KtraTGCa" Method="ft_KtraTGCa" IsComposable="true">
    <Parameter Name="dau" Type="System.TimeSpan" DbType="Time" />
    <Parameter Name="cuoi" Type="System.TimeSpan" DbType="Time" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.ft_TinhLuong" Method="ft_TinhLuong" IsComposable="true">
    <Parameter Name="ma" Type="System.Decimal" DbType="Decimal(6,0)" />
    <ElementType Name="ft_TinhLuongResult">
      <Column Name="MaCong" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SCKoLich" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SCDiLam" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SCNghi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SCKoPhep" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TienCongLam" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TienTru" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TienLuong" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>